### ISSUE TITLE
ros2_control_node with sudo

### ISSUE THREAD

**Issue by MattiaDeiRossi** [ros-controls/ros2_control_demos#317]
Hi all,
I would execute ros2_control_node with `root` privilegies.
I have a launch file equal to rrobot.launch.py but I have develop a plugin thath need sudo root to be exceuted because it use raw socket to send pkg to eno interface.

At the moment, I launch the node in this manner
```
    controller_manager_node = Node(
        package='controller_manager',
        executable='ros2_control_node',
        parameters=[robot_description_diz, controllers],
        output='both',
        on_exit=Shutdown()
    )
```

and launching the file with 
`sudo -s`
`source /opt/ros/galactic/setup.bash/; source install/setup.bash`
`ros2 launch ethercat_controllers controllers.launch.py use_fake_hardware:=true`

the output is
```
[spawner-2] [INFO] [1687508621.874474234] [spawner_joint_state_broadcaster]: Waiting for '/controller_manager' node to exist
[spawner-4] [INFO] [1687508621.874958531] [spawner_CSV]: Waiting for '/controller_manager' node to exist
[spawner-4] [INFO] [1687508623.888387496] [spawner_CSV]: Waiting for '/controller_manager' node to exist
[spawner-2] [INFO] [1687508623.889407608] [spawner_joint_state_broadcaster]: Waiting for '/controller_manager' node to exist
[spawner-4] [INFO] [1687508625.902779689] [spawner_CSV]: Waiting for '/controller_manager' node to exist
[spawner-2] [INFO] [1687508625.904840341] [spawner_joint_state_broadcaster]: Waiting for '/controller_manager' node to exist
[spawner-4] [INFO] [1687508627.917192315] [spawner_CSV]: Waiting for '/controller_manager' node to exist
[spawner-2] [INFO] [1687508627.919605991] [spawner_joint_state_broadcaster]: Waiting for '/controller_manager' node to exist
[spawner-4] [INFO] [1687508629.929275000] [spawner_CSV]: Waiting for '/controller_manager' node to exist
[spawner-2] [INFO] [1687508629.932278399] [spawner_joint_state_broadcaster]: Waiting for '/controller_manager' node to exist
[spawner-4] [ERROR] [1687508631.941449752] [spawner_CSV]: Controller manager not available
[spawner-2] [ERROR] [1687508631.944341756] [spawner_joint_state_broadcaster]: Controller manager not available
[ERROR] [spawner-4]: process has died [pid 99, exit code 1, cmd '/opt/ros/galactic/lib/controller_manager/spawner CSV -c /controller_manager --ros-args --params-file /awaxis/install/axis135s800/share/axis135s800/config/axis.ros2_controllers.yaml'].
[ERROR] [spawner-2]: process has died [pid 94, exit code 1, cmd '/opt/ros/galactic/lib/controller_manager/spawner joint_state_broadcaster --controller-manager /controller_manager --ros-args'].
```

It seems that ros library aren't linked correctly

Do you have any suggestion about it?
Thanks

**Comment by olivier-stasse** [comment]
I can suggest to run a Control node with sudo and forwarding the appropriate environment variables here:
https://github.com/stack-of-tasks/ros2_control_bolt/blob/caf548f1d7da2e1cde70e1e87e7e2928e351e663/ros2_control_bolt_bringup/launch/bolt.launch.py#L154

And it is better to run a sudo command before executing. the associated ```ros2 launch``` command. This way you avoid the need to type the password in the  flow of messages.

**Comment by MattiaDeiRossi** [comment]
Thank you for your answer,

I tried this method before and it works well.

Actually, I'm trying also to run the same code in a docker container but this workaround doesn't work here.
Have you tried it?

**Comment by olivier-stasse** [comment]
The CI tests are realized in dockers so I would suggest that you have a look to the one used by the github actions and the closest to your setup. 
Otherwise, if you need help on your specific Dockerfile, it is better to provide a minimal example highlighting your current problem.

**Comment by MattiaDeiRossi** [comment]
I tried to use Dockerfile similar to [https://github.com/ros-controls/ros2_control_demos/tree/master/Dockerfile](Dockerfile). That's my file:

```
# FROM ubuntu:focal
FROM ros:galactic-ros-base
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update \
    && apt-get upgrade -y

WORKDIR /awaxis
ADD . .
RUN rosdep install -y --from-paths src --ignore-src --include-eol-distros --rosdistro=galactic
RUN . /opt/ros/galactic/setup.sh; colcon build
```

My launch file that need sudo privileged is:
```
'''
    Authors: Mattia Dei Rossi 
'''
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, Shutdown
from launch.substitutions import Command, FindExecutable, LaunchConfiguration, EnvironmentVariable
from launch_ros.actions import Node
from launch import LaunchDescription
from launch.substitutions import PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.substitutions import FindPackageShare
from launch_ros.actions import Node
from ament_index_python.packages import get_package_share_directory
import os


def generate_launch_description():

    # args
    use_fake_hardware_name = 'use_fake_hardware'
    mode_of_op_name = 'mode_of_op'
    iname_name = 'iname'
    args = [
        DeclareLaunchArgument(
            use_fake_hardware_name,
            default_value='false',
            description='Use fake controllers'),
        DeclareLaunchArgument(
            mode_of_op_name,
            default_value="CSV",
            description='Mode of Operation desired. Available options: CSP,CSV,CST,HM,PP,PV,PT',
        ),
        DeclareLaunchArgument(
            iname_name,
            default_value="eno2",
            description='EtherCAT NIC interface name',
        )
    ]

    use_fake_hardware = LaunchConfiguration(use_fake_hardware_name)
    mode_of_op = LaunchConfiguration(mode_of_op_name)
    iname = LaunchConfiguration(iname_name)

    # load robot description
    xacro_file = os.path.join(get_package_share_directory(
        'axis135s800'), 'robots', 'axis135s800.urdf.xacro')
    robot_description = Command([FindExecutable(
        name='xacro'), ' ', xacro_file, ' use_fake_hardware:=', use_fake_hardware, ' mode_of_op:=', mode_of_op, ' iname:=', iname])
    robot_description_diz = {'robot_description': robot_description}

    # load controllers
    controllers = PathJoinSubstitution([FindPackageShare(
        'axis135s800'), 'config', 'axis.ros2_controllers.yaml'])

    # Nodes
    controller_manager_node = Node(
        package='controller_manager',
        prefix=[  # Sudo command cause need to be sudoer when we do this node cause it real time
                "sudo -E env PATH=",
                EnvironmentVariable("PATH", default_value="${PATH}"),
                " LD_LIBRARY_PATH=",
                EnvironmentVariable("LD_LIBRARY_PATH",
                                    default_value="${LD_LIBRARY_PATH}"),
                " PYTHONPATH=",
                EnvironmentVariable(
                    "PYTHONPATH", default_value="${PYTHONPATH}"),
                " HOME=/tmp ",
        ],
        executable='ros2_control_node',
        parameters=[robot_description_diz, controllers],
        output='both',
        on_exit=Shutdown()
    )

    joint_state_broadcaster = Node(
        package='controller_manager',
        executable='spawner',
        arguments=[
            'joint_state_broadcaster', "--controller-manager", "/controller_manager",
        ],
        output='screen'
    )

    controller = Node(
        package='controller_manager',
        executable='spawner',
        arguments=[
            mode_of_op, "-c", "/controller_manager",
        ],
        parameters=[controllers],
        output='screen'
    )

    robot_state_publisher = Node(
        package='robot_state_publisher',
        executable='robot_state_publisher',
        name='robot_state_publisher',
        output='both',
        parameters=[robot_description_diz]
    )

    nodes = [
        controller_manager_node,
        joint_state_broadcaster,
        robot_state_publisher,
        controller,
    ]

    return LaunchDescription(args + nodes)
```

I attach my log using `sh shell`
```
# . install/setup.sh
# . /opt/ros/galactic/setup.sh  
# ros2 launch ethercat_controllers controllers.launch.py use_fake_hardware:=true                                                 
[INFO] [launch]: All log files can be found below /root/.ros/log/2023-06-23-11-21-35-796052-mattia-Latitude-5510-57
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [ros2_control_node-1]: process started with pid [61]
[INFO] [spawner-2]: process started with pid [63]
[INFO] [robot_state_publisher-3]: process started with pid [65]
[INFO] [spawner-4]: process started with pid [67]
[robot_state_publisher-3] The root link axis135s800_root has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
[robot_state_publisher-3] Link axis135s800_end had 0 children
[robot_state_publisher-3] Link axis135s800_mounting_point had 0 children
[robot_state_publisher-3] Link axis135s800_start had 0 children
[robot_state_publisher-3] [INFO] [1687519296.166488021] [robot_state_publisher]: got segment axis135s800_end
[robot_state_publisher-3] [INFO] [1687519296.166563607] [robot_state_publisher]: got segment axis135s800_mounting_point
[robot_state_publisher-3] [INFO] [1687519296.166576725] [robot_state_publisher]: got segment axis135s800_root
[robot_state_publisher-3] [INFO] [1687519296.166585213] [robot_state_publisher]: got segment axis135s800_start
[ros2_control_node-1] [INFO] [1687519296.179692915] [controller_manager]: update rate is 1000 Hz
[ros2_control_node-1] [INFO] [1687519296.179973700] [controller_manager]: RT kernel is recommended for better performance
[spawner-2] [INFO] [1687519296.337120249] [spawner_joint_state_broadcaster]: Waiting for '/controller_manager' node to exist
[spawner-4] [INFO] [1687519296.337160428] [spawner_CSV]: Waiting for '/controller_manager' node to exist
[spawner-2] [INFO] [1687519298.349775767] [spawner_joint_state_broadcaster]: Waiting for '/controller_manager' node to exist
[spawner-4] [INFO] [1687519298.349775390] [spawner_CSV]: Waiting for '/controller_manager' node to exist
[spawner-2] [INFO] [1687519300.361239593] [spawner_joint_state_broadcaster]: Waiting for '/controller_manager' node to exist
[spawner-4] [INFO] [1687519300.361251334] [spawner_CSV]: Waiting for '/controller_manager' node to exist
^C[WARNING] [launch]: user interrupted with ctrl-c (SIGINT)
[ros2_control_node-1] [INFO] [1687519302.169587512] [rclcpp]: signal_handler(signal_value=2)
[robot_state_publisher-3] [INFO] [1687519302.169592028] [rclcpp]: signal_handler(signal_value=2)
[spawner-4] Traceback (most recent call last):
[spawner-4]   File "/opt/ros/galactic/lib/controller_manager/spawner", line 20, in <module>
[spawner-4]     ret = main()
[spawner-4]   File "/opt/ros/galactic/lib/controller_manager/spawner.py", line 162, in main
[spawner-4]     if not wait_for_controller_manager(node, controller_manager_name,
[spawner-4]   File "/opt/ros/galactic/lib/controller_manager/spawner.py", line 95, in wait_for_controller_manager
[spawner-4]     node_and_namespace = wait_for_value_or(
[spawner-4]   File "/opt/ros/galactic/lib/controller_manager/spawner.py", line 57, in wait_for_value_or
[spawner-4]     time.sleep(0.2)
[spawner-4] KeyboardInterrupt
[spawner-2] Traceback (most recent call last):
[spawner-2]   File "/opt/ros/galactic/lib/controller_manager/spawner", line 20, in <module>
[spawner-2]     ret = main()
[spawner-2]   File "/opt/ros/galactic/lib/controller_manager/spawner.py", line 162, in main
[spawner-2]     if not wait_for_controller_manager(node, controller_manager_name,
[spawner-2]   File "/opt/ros/galactic/lib/controller_manager/spawner.py", line 95, in wait_for_controller_manager
[spawner-2]     node_and_namespace = wait_for_value_or(
[spawner-2]   File "/opt/ros/galactic/lib/controller_manager/spawner.py", line 57, in wait_for_value_or
[spawner-2]     time.sleep(0.2)
[spawner-2] KeyboardInterrupt
[INFO] [robot_state_publisher-3]: process has finished cleanly [pid 65]
[INFO] [ros2_control_node-1]: process has finished cleanly [pid 61]
[INFO] [launch]: process[ros2_control_node-1] was required: shutting down launched system
[ERROR] [spawner-4]: process has died [pid 67, exit code -2, cmd '/opt/ros/galactic/lib/controller_manager/spawner CSV -c /controller_manager --ros-args --params-file /awaxis/install/axis135s800/share/axis135s800/config/axis.ros2_controllers.yaml'].
[ERROR] [spawner-2]: process has died [pid 63, exit code -2, cmd '/opt/ros/galactic/lib/controller_manager/spawner joint_state_broadcaster --controller-manager /controller_manager --ros-args'].
```
In `ros2_controller.xacro` s describe the param `use_fake_hardware` 
```
<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="axis135s800_ros2_control"
    params="use_fake_hardware:=^|true id:=axis135s800 mode_of_op:=PP iname:=eno2">

    <ros2_control name="awaxis" type="system">
      <hardware>
        <xacro:if value="${use_fake_hardware}">
          <plugin>fake_components/GenericSystem</plugin>
        </xacro:if>
        <xacro:unless value="${use_fake_hardware}">
          <plugin>ethercat_driver/EthercatDriver</plugin>
          <param name="interface_name">${iname}</param>
          <param name="cpu_id">0</param>
          <param name="control_frequency">1000</param>
        </xacro:unless>
      </hardware>
```
I don't find any issue here, What am I doing wrong?
With

**Comment by MattiaDeiRossi** [comment]
My Dockerfile is similar to that one [Dockerfile](https://github.com/ros-controls/ros2_control_demos/blob/master/Dockerfile/Dockerfile), but I still have that issue
```
FROM ros:galactic-ros-base

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update \
    && apt-get upgrade -y

WORKDIR /awaxis
ADD . .

RUN rosdep install -y --from-paths src --ignore-src --include-eol-distros --rosdistro=galactic
RUN . /opt/ros/galactic/setup.sh; colcon build

```

My launch file is
```
'''
    Copyright Ⓒ Automationware 2023
    Authors: Mattia Dei Rossi (deirossi@automationware.it)
'''
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, Shutdown
from launch.substitutions import Command, FindExecutable, LaunchConfiguration, EnvironmentVariable
from launch_ros.actions import Node
from launch import LaunchDescription
from launch.substitutions import PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.substitutions import FindPackageShare
from launch_ros.actions import Node
from ament_index_python.packages import get_package_share_directory
import os


def generate_launch_description():

    # args
    use_fake_hardware_name = 'use_fake_hardware'
    mode_of_op_name = 'mode_of_op'
    iname_name = 'iname'
    args = [
        DeclareLaunchArgument(
            use_fake_hardware_name,
            default_value='false',
            description='Use fake controllers'),
        DeclareLaunchArgument(
            mode_of_op_name,
            default_value="CSV",
            description='Mode of Operation desired. Available options: CSP,CSV,CST,HM,PP,PV,PT',
        ),
        DeclareLaunchArgument(
            iname_name,
            default_value="eno2",
            description='EtherCAT NIC interface name',
        )
    ]

    use_fake_hardware = LaunchConfiguration(use_fake_hardware_name)
    mode_of_op = LaunchConfiguration(mode_of_op_name)
    iname = LaunchConfiguration(iname_name)

    # load robot description
    xacro_file = os.path.join(get_package_share_directory(
        'axis135s800'), 'robots', 'axis135s800.urdf.xacro')
    robot_description = Command([FindExecutable(
        name='xacro'), ' ', xacro_file, ' use_fake_hardware:=', use_fake_hardware, ' mode_of_op:=', mode_of_op, ' iname:=', iname])
    robot_description_diz = {'robot_description': robot_description}

    # load controllers
    controllers = PathJoinSubstitution([FindPackageShare(
        'axis135s800'), 'config', 'axis.ros2_controllers.yaml'])

    # Nodes
    controller_manager_node = Node(
        package='controller_manager',
        prefix=[  # Sudo command cause need to be sudoer when we do this node cause it real time
                "sudo -E env PATH=",
                EnvironmentVariable("PATH", default_value="${PATH}"),
                " LD_LIBRARY_PATH=",
                EnvironmentVariable("LD_LIBRARY_PATH",
                                    default_value="${LD_LIBRARY_PATH}"),
                " PYTHONPATH=",
                EnvironmentVariable(
                    "PYTHONPATH", default_value="${PYTHONPATH}"),
                " HOME=/tmp ",
        ],
        executable='ros2_control_node',
        parameters=[robot_description_diz, controllers],
        output='both',
        on_exit=Shutdown()
    )

    joint_state_broadcaster = Node(
        package='controller_manager',
        executable='spawner',
        arguments=[
            'joint_state_broadcaster', "--controller-manager", "/controller_manager",
        ],
        output='screen'
    )

    controller = Node(
        package='controller_manager',
        executable='spawner',
        arguments=[
            mode_of_op, "-c", "/controller_manager",
        ],
        parameters=[controllers],
        output='screen'
    )

    robot_state_publisher = Node(
        package='robot_state_publisher',
        executable='robot_state_publisher',
        name='robot_state_publisher',
        output='both',
        parameters=[robot_description_diz]
    )

    nodes = [
        controller_manager_node,
        joint_state_broadcaster,
        robot_state_publisher,
        controller,
    ]

    return LaunchDescription(args + nodes)

```

I don't find any issue here, What am I wrong?

**Comment by MattiaDeiRossi** [comment]
I solve the issue, 

the problem is something related to my `docker_compose.yaml`file, 
Thank you for your help

**Comment by MattiaDeiRossi** [comment]
I solve the issue,

the problem is something related to my docker_compose.yamlfile,
Thank you for your help

**Comment by christophfroehlich** [comment]
Just for completeness: I have a similar setup, where the hardware component needs root privileges for a proprietary shared memory interface, launched in a sh-shell.

I wrote a sh-script with similar contents to yours, i.e., sourcing the workspace and the `ros2 launch command`, which I then launch with `sudo sh start.sh`
This can also be installed as a systemd service with 
```
[Service]
User=root
ExecStart=<path/to>start.sh
```
